### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dotZoki** [lecode-official/command-line-parser#1]
Some documentation how to use it wouldn't be bad - in spite the samples.

**Comment by lecode-official** [comment]
Yeah, you are right. for now, unfortunately I have no time to write up some documentation. But this will definitely come in the future. For now you may find all use cases in the unit tests.

**Comment by lecode-official** [comment]
I am planning on completely rewriting the Command Line Parser. This will go hand in hand with the transition to .NET Core. Once the new version is there, I will write up some extensive documentation. As I won't be fixing this right now, I will close the issue.
