### ISSUE TITLE
Colon ':' character should be valid for unquoted values

### ISSUE THREAD

**Issue by dPJinjo** [lecode-official/command-line-parser#3]
I think the colon character ':' should be valid for parameter values that are unquoted.  Example "-p C:\\\\dir\\\\file.ext" fails at the ':' in the input after the drive letter.  I think this example input should be valid.  Your g4 explicitly forbids it.

**Comment by lecode-official** [comment]
You are absolutely right. This should be possible. As I explained in more detail in issue #2, I will completely rewrite the Command Line Parser in the future. Then I will make sure that this feature will work. As I will not address this issue right now, I will close the issue, but please feel welcome to send me a working pull request if you really need this feature.
